#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <flipper_control_icons.h>

int32_t flipper_control_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm flipper_control!");

    return 0;
}
